# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.TextField(verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('checked', models.BooleanField(default=False, verbose_name='Is Checked')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Check date')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('adress', models.CharField(default='', max_length=100, verbose_name='Adress')),
                ('telephone', models.CharField(max_length=100, verbose_name='Telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=100, verbose_name='Text')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.TextField(verbose_name='Image')),
                ('views', models.IntegerField(verbose_name='Views')),
                ('price', models.FloatField(verbose_name='Price')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Producer', verbose_name='Producer')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
